version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: devops
    depends_on:
      - mysql
    networks:
      - app-network
    command: ["npm", "test"]

  mysql:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: devops
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
